apiVersion: v1
kind: PersistentVolume
metadata:
  name: azurefile-pv
spec:
  capacity:
    storage: 100Gi

  accessModes:
    - ReadWriteMany

  persistentVolumeReclaimPolicy: Retain

  storageClassName: azurefile-managed-identity

  csi:
    driver: file.csi.azure.com

    volumeHandle: "akssharedo3ue-aks-shared"

    volumeAttributes:
      resourceGroup: "1-oct"
      storageAccount: "akssharedo3ue"
      shareName: "aks-shared"
      protocol: "smb"
      mountWithManagedIdentity: "true"

  mountOptions:
    - dir_mode=0755
    - file_mode=0755
    - mfsymlinks
    - cache=strict
    - nosharesock
    - actimeo=30
