apiVersion: v1
kind: Secret
metadata:
  name: secret-basic-auth
  labels:
        app: api
        env: dev
  namespace: nginx-app
#type: kubernetes.io/basic-auth
# k apply -f .\secrets.yml
# The Secret "secret-basic-auth" is invalid:
# * data[username]: Required value
# * data[password]: Required value
type: Opaque
stringData:
  DATABASE_PASSWORD: admin # required field for kubernetes.io/basic-auth
  DATABASE_USER: t0p-Secret # required field for kubernetes.io/basic-auth