apiVersion: apps/v1
kind: Deployment

metadata:
  name: learning-app
  namespace: learning

spec:
  replicas: 2

  selector:
    matchLabels:
      app: learning-app

  template:
    metadata:
      labels:
        app: learning-app

    spec:
      containers:
      - name: nginx
        image: nginx:latest

        ports:
        - containerPort: 80

        env:
        - name: APP_NAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: APP_NAME

        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: ENVIRONMENT

        - name: MESSAGE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MESSAGE

        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: USERNAME

        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: PASSWORD