services = [
    {"service_name": "auth", "status": 200, "response_time_ms": 120},
    {"service_name": "auth", "status": 200, "response_time_ms": 105},
    {"service_name": "auth", "status": 200, "response_time_ms": 135},
    {"service_name": "auth", "status": 403, "response_time_ms": 95},
    {"service_name": "auth", "status": 403, "response_time_ms": 110},
    {"service_name": "auth", "status": 500, "response_time_ms": 350},
    {"service_name": "auth", "status": 401, "response_time_ms": 85},
    {"service_name": "auth", "status": 200, "response_time_ms": 125},

    {"service_name": "payments", "status": 200, "response_time_ms": 210},
    {"service_name": "payments", "status": 200, "response_time_ms": 195},
    {"service_name": "payments", "status": 200, "response_time_ms": 225},
    {"service_name": "payments", "status": 403, "response_time_ms": 115},
    {"service_name": "payments", "status": 403, "response_time_ms": 125},
    {"service_name": "payments", "status": 500, "response_time_ms": 480},
    {"service_name": "payments", "status": 502, "response_time_ms": 520},
    {"service_name": "payments", "status": 201, "response_time_ms": 240},

    {"service_name": "orders", "status": 200, "response_time_ms": 175},
    {"service_name": "orders", "status": 200, "response_time_ms": 160},
    {"service_name": "orders", "status": 200, "response_time_ms": 190},
    {"service_name": "orders", "status": 403, "response_time_ms": 105},
    {"service_name": "orders", "status": 403, "response_time_ms": 120},
    {"service_name": "orders", "status": 404, "response_time_ms": 130},
    {"service_name": "orders", "status": 500, "response_time_ms": 410},
    {"service_name": "orders", "status": 201, "response_time_ms": 180},

    {"service_name": "inventory", "status": 200, "response_time_ms": 145},
    {"service_name": "inventory", "status": 200, "response_time_ms": 155},
    {"service_name": "inventory", "status": 200, "response_time_ms": 140},
    {"service_name": "inventory", "status": 403, "response_time_ms": 100},
    {"service_name": "inventory", "status": 403, "response_time_ms": 115},
    {"service_name": "inventory", "status": 503, "response_time_ms": 620},
    {"service_name": "inventory", "status": 500, "response_time_ms": 450},
    {"service_name": "inventory", "status": 200, "response_time_ms": 165},

    {"service_name": "auth", "status": 200, "response_time_ms": 118},
    {"service_name": "payments", "status": 403, "response_time_ms": 108},
    {"service_name": "orders", "status": 200, "response_time_ms": 172},
    {"service_name": "inventory", "status": 200, "response_time_ms": 152},
    {"service_name": "auth", "status": 403, "response_time_ms": 102},
    {"service_name": "payments", "status": 200, "response_time_ms": 205},
    {"service_name": "orders", "status": 403, "response_time_ms": 118},
    {"service_name": "inventory", "status": 200, "response_time_ms": 148},
]

