apiVersion: v1
kind: PersistentVolume
metadata:
  name: azure-disk-pv
  annotations:
    pv.kubernetes.io/provisioned-by: disk.csi.azure.com
spec:
  capacity:
    storage: 90Gi # have created 100GiB disk on Aure - 90 just isdb - not use full capacity

  accessModes:
    - ReadWriteOnce

  persistentVolumeReclaimPolicy: Retain

  storageClassName: managed-csi

  csi:
    driver: disk.csi.azure.com
    volumeHandle: "/subscriptions/99d8f8e9-1b37-4b2d-b102-416a5bc55c43/resourceGroups/k8ss/providers/Microsoft.Compute/disks/aks-disk"
    volumeAttributes:
      fsType: ext4
